"""
SalesPulse — Executive BI REST API Server
Provides endpoints for dataset ingestion, data profiling, multi-attribute filtering,
and executive report generation.
"""

import os
from flask import Flask, request, jsonify, Response
from flask_cors import CORS
from pipeline import SalesPulsePipeline
from profiler import DataProfiler
from db_loader import init_db, load_transactions_to_db, query_sales_summary

app = Flask(__name__)
CORS(app)

# Initialize database
init_db()

pipeline = SalesPulsePipeline()
profiler = DataProfiler()

# Pre-ingest default dataset if exists
if os.path.exists("data/transactions.csv"):
    pipeline.ingest_data("data/transactions.csv")
    load_transactions_to_db(pipeline.records)

@app.route('/api/health', methods=['GET'])
def health():
    return jsonify({
        "status": "online",
        "service": "SalesPulse BI Engine",
        "version": "2.0.0",
        "capabilities": ["iqr_outlier_detection", "data_profiling", "mom_growth", "executive_reporting"]
    })

@app.route('/api/upload', methods=['POST'])
def upload_dataset():
    """Uploads and profiles custom CSV sales dataset."""
    if 'file' not in request.files:
        return jsonify({"error": "No file uploaded"}), 400

    file = request.files['file']
    if file.filename == '':
        return jsonify({"error": "No file selected"}), 400

    upload_dir = os.path.join(os.path.dirname(__file__), "uploads")
    os.makedirs(upload_dir, exist_ok=True)
    file_path = os.path.join(upload_dir, file.filename)
    file.save(file_path)

    try:
        records = pipeline.ingest_data(file_path)
        load_transactions_to_db(records)
        profile_data = profiler.profile_dataset(records)
        analytics = pipeline.get_filtered_analytics()
        return jsonify({
            "message": "Dataset successfully uploaded and processed.",
            "profile": profile_data,
            "analytics": analytics,
            "sample_records": records[:50]
        })
    finally:
        if os.path.exists(file_path):
            os.remove(file_path)

@app.route('/api/analytics', methods=['GET'])
def get_analytics():
    """Returns computed analytics based on region, category, and date query filters."""
    region = request.args.get('region')
    category = request.args.get('category')
    start_date = request.args.get('start_date')
    end_date = request.args.get('end_date')

    data = pipeline.get_filtered_analytics(
        region=region,
        category=category,
        start_date=start_date,
        end_date=end_date
    )
    return jsonify(data)

@app.route('/api/profile', methods=['GET'])
def get_profile():
    """Returns data quality scorecard and health score."""
    if not pipeline.records:
        pipeline.ingest_data()
    return jsonify(profiler.profile_dataset(pipeline.records))

@app.route('/api/transactions', methods=['GET'])
def get_transactions():
    """Returns paginated or sliced transactions for data table inspection."""
    limit = int(request.args.get('limit', 100))
    if not pipeline.records:
        pipeline.ingest_data()
    return jsonify({
        "total": len(pipeline.records),
        "records": pipeline.records[:limit]
    })

@app.route('/api/export/summary', methods=['GET'])
def export_summary():
    """Generates an executive narrative report in Markdown."""
    analytics = pipeline.get_filtered_analytics()
    profile = profiler.profile_dataset(pipeline.records)

    report = f"""# SalesPulse — Executive Financial Briefing
Generated: {os.popen('date /t').read().strip() if os.name == 'nt' else 'Today'}

## 1. Executive Summary & KPIs
- **Gross Invoiced Revenue:** ${analytics['total_revenue']:,.2f}
- **Net Operating Profit:** ${analytics['total_profit']:,.2f}
- **Average Profit Margin:** {analytics['profit_margin_pct']}%
- **Month-over-Month Growth:** {analytics['mom_growth_pct']}%
- **Average Order Value (AOV):** ${analytics['average_order_value']:,.2f}
- **Total Validated Transactions:** {analytics['total_transactions']:,}

## 2. Regional & Product Drivers
- **Leading Territory:** {analytics['top_region']}
- **Top Product Category:** {analytics['top_category']}

## 3. Data Integrity & Health Scorecard
- **Data Health Score:** {profile['health_score']}/100 (Grade: {profile['grade']})
- **Total Ingested Rows:** {profile['total_rows']:,}
- **Statistical Outliers Flagged (IQR):** {profile['outliers_detected']}
- **Missing / Null Cells:** {profile['missing_cells']}

---
*Report auto-generated by SalesPulse Analytics Pipeline.*
"""
    return Response(report, mimetype='text/markdown', headers={"Content-Disposition": "attachment;filename=executive_sales_summary.md"})

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5001, debug=True)
